### ISSUE TITLE
Runsheet for MACS2

### ISSUE THREAD

**Issue by huipan1973** [scfurl/henipipe#4]
I have difficulty in running the test data using MACS2

Here are the first 4 columns of my runsheet:

![image](https://user-images.githubusercontent.com/4342926/109405566-bca89f00-793f-11eb-9f0d-51500b80c117.png)

Here is the error message:
Traceback (most recent call last):
  File "/home/panh/.local/bin/henipipe", line 8, in <module>
    sys.exit(run_henipipe())
  File "/home/panh/.local/pipx/venvs/henipipe/lib/python3.7/site-packages/henipipe/__main__.py", line 166, in run_henipipe
    MACS2job = henipipe.MACS2(runsheet_data = parsed_runsheet, threads = args.threads, gb_ram = args.gb_ram, debug=args.debug, cluster=args.cluster, user=args.user, log=args.log_prefix, out=args.output)
  File "/home/panh/.local/pipx/venvs/henipipe/lib/python3.7/site-packages/henipipe/henipipe.py", line 402, in __init__
    self.script = self.environs.generate_job(self,commands, self.job)
NameError: name 'commands' is not defined

**Comment by scfurl** [comment]
Hi Hui,

Sorry for the delay.  I haven’t fully developed the MACS2 pipeline.  It
worked at one point but updates to the cluster have probably broken the
workflow.

I know that this email is pretty old, but were you able to figure this out?

S


On February 27, 2021 at 2:19:58 PM, Hui Pan ***@***.***)
wrote:

I have difficulty in running the test data using MACS2

Here are my first 4 columns of my runsheet:

sample SEACR_key MACS2_key MERGE_key
4G1_IgG 4G1_CONTROL 41 4G1_IgG
4G1_H3K27me3 4G1 41_CONTROL 4G1_H3K27me3
4N1_H3K27me3 4N1 41 4N1_H3K27me3
4N2_H3K27me3 4N2 42 4N2_H3K27me3
4G2_IgG 4G2_CONTROL 42 4G2_IgG
4N1_IgG 4N1_CONTROL 41 4N1_IgG
4G2_H3K27me3 4G2 42_CONTROL 4G2_H3K27me3
4N2_IgG 4N2_CONTROL 42 4N2_IgG

Here is the error message:
Traceback (most recent call last):
File "/home/panh/.local/bin/henipipe", line 8, in
sys.exit(run_henipipe())
File
"/home/panh/.local/pipx/venvs/henipipe/lib/python3.7/site-packages/henipipe/
*main*.py", line 166, in run_henipipe
MACS2job = henipipe.MACS2(runsheet_data = parsed_runsheet, threads =
args.threads, gb_ram = args.gb_ram, debug=args.debug, cluster=args.cluster,
user=args.user, log=args.log_prefix, out=args.output)
File
"/home/panh/.local/pipx/venvs/henipipe/lib/python3.7/site-packages/henipipe/henipipe.py",
line 402, in *init*
self.script = self.environs.generate_job(self,commands, self.job)
NameError: name 'commands' is not defined

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scfurl/henipipe/issues/4>, or unsubscribe

**Comment by huipan1973** [comment]
Thanks for the message. I haven't figured out yet.

Regards,

Hui

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
