### ISSUE TITLE
HENIPIPE_SEACR issue

### ISSUE THREAD

**Issue by gianfilippo** [scfurl/henipipe#8]
Hi,

I am running your pipeline on a few of my samples and everything seemed well, until I started to get the following error 
awk: cmd. line:1: fatal: division by zero attempted
Only on some samples, running
henipipe SEACR -r $outDIR/$runsheetFILE -Ss relaxed -Sn norm -v

I have to add that 
henipipe AUC -r $outDIR/runsheet.csv -o auc -v
does not work for me at all, even when every other step works.
I get the error below.

Anything I am doing wrong ?

Thanks

Traceback (most recent call last):
  File "$PATH/.local/bin/henipipe", line 8, in <module>
    sys.exit(run_henipipe())
  File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/__main__.py", line 235, in run_henipipe
    AUCjob = henipipe.AUC(runsheet_data = parsed_runsheet, threads = args.threads, gb_ram = args.gb_ram, debug=args.debug, no_pipe=args.keep_files, cluster=args.cluster, user=args.user, log=args.log_prefix, out=args.output, norm=args.SEACR_norm, stringency=args.SEACR_stringency)
  File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 681, in __init__
    self.runsheet_data = self.AUC_match()
  File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 698, in AUC_match
    is_biomatch_control = [bool(re.search(r'._CONTROL$', i)) for i in biomatch_key]
  File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 698, in <listcomp>
    is_biomatch_control = [bool(re.search(r'._CONTROL$', i)) for i in biomatch_key]
  File "/gpfs/ycga/project/coppola/$USER/conda_envs/henipipe/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by scfurl** [comment]
Hi Gianfilippo,

I am sorry but don’t recognize that error.  I suspect it may be a SEACR problem…

Would you mind trying to run the files manually using SEACR and letting me know if it goes?
https://github.com/FredHutch/SEACR

I am not sure about the AUC error.  Did you edit the AUC columns in the runsheet, if so can you send your runsheet?

Best

S


From: Gianfilippo Coppola ***@***.***>
Date: Saturday, October 22, 2022 at 12:10 PM
To: scfurl/henipipe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [scfurl/henipipe] HENIPIPE_SEACR issue (Issue #8)

Hi,

I am running your pipeline on a few of my samples and everything seemed well, until I started to get the following error
awk: cmd. line:1: fatal: division by zero attempted
Only on some samples, running
henipipe SEACR -r $outDIR/$runsheetFILE -Ss relaxed -Sn norm -v

I have to add that
henipipe AUC -r $outDIR/runsheet.csv -o auc -v
does not work for me at all, even when every other step works.
I get the error below.

Anything I am doing wrong ?

Thanks

Traceback (most recent call last):
File "$PATH/.local/bin/henipipe", line 8, in
sys.exit(run_henipipe())
File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/main.py", line 235, in run_henipipe
AUCjob = henipipe.AUC(runsheet_data = parsed_runsheet, threads = args.threads, gb_ram = args.gb_ram, debug=args.debug, no_pipe=args.keep_files, cluster=args.cluster, user=args.user, log=args.log_prefix, out=args.output, norm=args.SEACR_norm, stringency=args.SEACR_stringency)
File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 681, in init
self.runsheet_data = self.AUC_match()
File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 698, in AUC_match
is_biomatch_control = [bool(re.search(r'._CONTROL$', i)) for i in biomatch_key]
File "$PATH/.local/pipx/venvs/henipipe/lib/python3.10/site-packages/henipipe/henipipe.py", line 698, in
is_biomatch_control = [bool(re.search(r'._CONTROL$', i)) for i in biomatch_key]
File "/gpfs/ycga/project/coppola/$USER/conda_envs/henipipe/lib/python3.10/re.py", line 200, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by gianfilippo** [comment]
Hi,

thanks. I will try to run SEACR directly and, in case, contact the authors.

As far as the AUC is concerned, I do not see any AUC column in there.
At the moment the columns are:
sample,SEACR_key,MERGE_key,fasta,spikein_fasta,genome_sizes,fastq1,fastq2,bed_out,spikein_bed_out,bedgraph,SEACR_out
Sample_MRCR1,Sample_MRCR4_CONTROL,Sample_MRCR1,$PATH/GRCh38.p13/GRCh38.p13.genome,$PATH/U00096.3/U00096.3,$PATH/ChromSize.txt,$FASTQ1,$FASTQ2,$BEDOUT,$SpikeInBEDOUT,$BEDGRAPH,$SEACRout
.............

the first row is simplified, I replaced entries with vars. Also, I used absolute paths for everything.

Best
